eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: SMC
      
spring:
  cloud:
    gateway:
      routes:
        - id: EMPLOYE-SERVICE
          uri: lb://EMPLOYE-SERVICE
          predicates:
            - Path=/employees/**
        - id: ROLE-SERVICE
          uri: lb://ROLE-SERVICE
          predicates: 
            - Path=/roles/**
